## 导航栏链接
menu:
  archives: "/archives/"
  about: "/about/"
  Feed: "/atom.xml"
  Note: "https://note.dgeibi.xyz"

## About
twitter: dgeibi
github: dgeibi
email: png.inside@gmail.com

rss:
  type: application/atom+xml
  href: /atom.xml

favicon:
  type: image/png
  href: /favicon.png

sitemap:
  type: application/xml
  href: /sitemap.xml